/**
 * Login placeholder. Auth & RBAC agent replaces this with a real Better Auth form.
 */
export default function LoginPage() {
  return (
    <main className="flex min-h-dvh items-center justify-center px-6">
      <div className="w-full max-w-sm rounded-md border p-6">
        <h1 className="text-lg font-semibold">Login</h1>
        <p className="mt-2 text-sm opacity-70">
          Login form pending — generated by the Auth &amp; RBAC agent.
        </p>
      </div>
    </main>
  );
}
