import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Atelier Generated App",
  description: "Generated by Atelier",
};

/**
 * Root layout — dark mode forzado + fuente del sistema. El agente
 * API & Frontend wrappea aquí el QueryClientProvider y el AuthProvider.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className="dark" suppressHydrationWarning>
      <body className="min-h-dvh bg-[hsl(var(--background))] text-[hsl(var(--foreground))] antialiased">
        {children}
      </body>
    </html>
  );
}
