/**
 * Dashboard placeholder. API & Frontend agent replaces with a per-role view.
 */
export default function DashboardPage() {
  return (
    <main className="px-6 py-8">
      <h1 className="text-xl font-semibold">Dashboard</h1>
      <p className="mt-2 text-sm opacity-70">
        Role-aware dashboard pending — generated by the API &amp; Frontend agent.
      </p>
    </main>
  );
}
