/**
 * F2.2 — Record a Stitch fixture for yoga.
 *
 * Calls @google/stitch-sdk directly (bypassing the StitchClient TypeScript
 * wrapper whose tool names don't match the real MCP — see V3_PROGRESS.md
 * deuda #11) to generate the 8 yoga pages, downloads their HTML, and
 * writes the result to `fixtures/stitch-yoga.json` in the attempt-aware
 * shape consumed by `prepareStitchFixtureForAttempt`.
 *
 * Strategy for attempt-awareness:
 *   - One real Stitch call per page = `attempt: 1` (the "corrected" set).
 *   - `attempt: 0` is generated by mutating the /sign-in HTML to REMOVE
 *     the <form> element, simulating "Stitch left the form out" — that's
 *     a gap the stitch-completeness-scanner detects (signin-form is a
 *     critical test-id on the public layoutGroup).
 *   - So `attempt: 0` exercises the reprompt loop:
 *       scanner emits `stitch-missing-critical-element` →
 *       orchestrator reprompts → fixture preparer materialises attempt 1 →
 *       scanner passes → wave converges.
 *
 * Quota cost: 1 createProject + 8 generate calls + 8 getHtml calls ≈
 * 8 Stitch generations (~3-6% of the free 350/month). Each `generate`
 * call may internally retry; the SDK does NOT expose internal retries
 * but auth/transport errors will hit the SDK's own backoff.
 *
 * No `--dry-run` flag: this script's job is to spend the quota once.
 * If you want to inspect the script without spending it, read the code
 * and exit (it's idempotent against the output file but NOT against the
 * Stitch backend — every run creates a new Stitch project).
 *
 * Usage:
 *   tsx scripts/record-stitch-yoga-fixture.ts
 *
 * Pre-conditions:
 *   - STITCH_API_KEY set in .env.local (loaded via dotenv below).
 *   - @google/stitch-sdk installed.
 *   - fixtures/yoga-prd.json present.
 *
 * Output:
 *   - fixtures/stitch-yoga.json (the attempt-aware fixture).
 *   - .atelier-fixtures/stitch-yoga-raw/<slug>.html (debug / inspection).
 */
import { mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, resolve } from "node:path";

import { config as loadDotenv } from "dotenv";

// @google/stitch-sdk is "type": "module" with no CJS "require" export entry.
// tsx executes scripts as CJS by default, so a top-level static import would
// fail with ERR_PACKAGE_PATH_NOT_EXPORTED. Use a dynamic import inside main()
// instead — works fine from a CJS host.
import type { StitchFixture } from "../lib/agents/contracts-v3/stitch-fixture.schema";
import { runGeneratorAgentV3 } from "../lib/agents/runtime/runner-generator-v3";

// Load .env.local (and .env as fallback) BEFORE the SDK reads the env var.
loadDotenv({ path: resolve(__dirname, "..", ".env.local") });
loadDotenv({ path: resolve(__dirname, "..", ".env") });

if (!process.env["STITCH_API_KEY"]) {
  console.error(
    "STITCH_API_KEY missing — set it in .env.local at the repo root before running this script.",
  );
  process.exit(2);
}

// ─── Yoga page roster (DERIVED from architect output, not hardcoded) ─
//
// B3 fix: previous version hardcoded routes from memory of the v2 yoga
// PRD. Those routes (`/shop`, `/my/classes`) did NOT match what the
// architect agent actually generates from the same PRD (`/classes`,
// `/my/agenda`). Result: the fixture's pageRoutes disagreed with the
// architect's pageRoutes downstream, forcing the Layout Architect into
// awkward route remapping. Fix is structural: run architect FIRST, use
// its routes verbatim.

interface YogaPage {
  route: string;
  routeSlug: string;
  purpose: string;
}

interface ArchitectFeature {
  name: string;
  useCases?: readonly string[];
  publicRoutes?: readonly string[];
  privateRoutes?: readonly string[];
  adminRoutes?: readonly string[];
}

interface ArchitectArtifact {
  features: ReadonlyArray<ArchitectFeature>;
}

function routeToSlug(route: string): string {
  if (route === "/") return "home";
  // Replace parameter syntax `[id]` with literal `id` so slugs stay kebab-case.
  return route
    .replace(/^\//, "")
    .replace(/\[([^\]]+)\]/g, "$1")
    .replace(/\//g, "-")
    .toLowerCase();
}

function flattenArchitectRoutes(architect: ArchitectArtifact): YogaPage[] {
  // Filter to keep quota cost similar to F2.2 (~8 generations ≈ 2-3% of
  // monthly cap). Strategy: ALL publicRoutes (these are usually 4-6),
  // plus the first private + first admin route per feature (caps growth
  // at 2 × features). Empirically yields 8-12 pages for yoga-scale PRDs.
  const out: YogaPage[] = [];
  const seen = new Set<string>();
  const push = (route: string, purpose: string) => {
    if (seen.has(route)) return;
    seen.add(route);
    out.push({ route, routeSlug: routeToSlug(route), purpose });
  };
  for (const f of architect.features) {
    const useCasesSummary = (f.useCases ?? []).join("; ") || "no use cases documented";
    for (const r of f.publicRoutes ?? []) {
      push(r, `${f.name} — public — ${useCasesSummary}`);
    }
    const firstPriv = (f.privateRoutes ?? [])[0];
    if (firstPriv) push(firstPriv, `${f.name} — authenticated — ${useCasesSummary}`);
    const firstAdmin = (f.adminRoutes ?? [])[0];
    if (firstAdmin) push(firstAdmin, `${f.name} — admin — ${useCasesSummary}`);
  }
  // Implicit auth pages — architect doesn't always list them; ensure they
  // exist for Stitch so /sign-in and /sign-up always render.
  if (!seen.has("/sign-in")) {
    push("/sign-in", "Auth — sign-in form, email + password, link to /sign-up");
  }
  if (!seen.has("/sign-up")) {
    push("/sign-up", "Auth — sign-up form, name + email + password, link to /sign-in");
  }
  return out;
}

// ─── Architect run (B3 fix — discover routes from the canonical pipeline) ─

async function runArchitectForYogaPrd(): Promise<ArchitectArtifact> {
  const repoRoot = resolve(__dirname, "..");
  const tmpDir = join(repoRoot, ".atelier-fixtures", "_recorder-architect-tmp");

  // Clean tmp dir to ensure a fresh architect run (idempotent across re-recordings).
  if (existsSync(tmpDir)) await rm(tmpDir, { recursive: true, force: true });
  await mkdir(join(tmpDir, ".atelier"), { recursive: true });

  // Inject discovery from the yoga PRD verbatim (same shim as the main script).
  const prdRaw = await readFile(join(repoRoot, "fixtures", "yoga-prd.json"), "utf8");
  await writeFile(join(tmpDir, ".atelier", "discovery.json"), prdRaw, "utf8");
  log("architect", "discovery.json injected into temp workdir");

  // Load v2 architect prompt (architect is v2-reused in v3).
  const systemPrompt = await readFile(
    join(repoRoot, "lib", "agents", "prompts-v2", "architect.md"),
    "utf8",
  );

  log("architect", "spawning architect agent (~1 min)...");
  const result = await runGeneratorAgentV3({
    agent: "architect",
    systemPrompt,
    contextArtifacts: { discovery: true },
    workDir: tmpDir,
  });
  if (result.status === "failed") {
    throw new Error(`architect agent failed: ${result.error ?? "(no error message)"}`);
  }
  if (result.artifact === null || result.artifact === undefined) {
    throw new Error("architect produced no artifact");
  }
  log("architect", `✓ done — ${result.stopSentinel ?? "(no sentinel)"}`);
  return result.artifact as ArchitectArtifact;
}

// ─── Prompt builder ────────────────────────────────────────────────

function buildStitchPrompt(pages: readonly YogaPage[]): string {
  return [
    "You are designing a Calm-style yoga studio web application.",
    "",
    "Functional context:",
    "- Platform for managing a yoga studio: students book classes, teachers run sessions, admins manage memberships and the catalogue.",
    "- Roles: admin, teacher, student.",
    "- Primary entities: User, Class, Booking, Membership.",
    "",
    "Visual hints (tentative — feel free to adapt):",
    "- primarySeed: #4a7c59 (salvia green; calm, natural)",
    "- vibeMood: calm",
    "- sansSuggestion: Inter (or DM Sans)",
    "- displaySuggestion: Cormorant Garamond (for hero headings)",
    "- voice: calm / tone: intimate (microcopy will be injected later by the Visual Adapter)",
    "",
    "Pages to design:",
    ...pages.map((p) => `- ${p.route}: ${p.purpose}`),
    "",
    "For each page: full responsive layout with header containing logo + nav + 'Sign in' CTA on public pages; consistent footer; sections sized for a typical 1280×800 viewport.",
  ].join("\n");
}

// ─── Per-page generation ───────────────────────────────────────────

const TAG_START = Date.now();
function ts(): string {
  return new Date().toISOString().slice(11, 23);
}
function log(stage: string, msg: string): void {
  console.log(`[${ts()}] [${stage}] ${msg}`);
}

interface GeneratedScreen {
  screenId: string;
  routeSlug: string;
  pageRoute: string;
  rawHtml: string;
}

async function generateAllScreens(pages: readonly YogaPage[]): Promise<{ projectId: string; designMd: string; screens: GeneratedScreen[] }> {
  // Dynamic import (see note at top of file).
  const sdk = (await import("@google/stitch-sdk")) as typeof import("@google/stitch-sdk");
  const { stitch } = sdk;

  log("stitch", "creating Stitch project 'Atelier-Yoga-V3-Fixture'...");
  const project = await stitch.createProject("Atelier-Yoga-V3-Fixture");
  log("stitch", `project ready: ${project.projectId}`);

  const screens: GeneratedScreen[] = [];
  const fullPrompt = buildStitchPrompt(pages);

  for (const page of pages) {
    log("stitch", `generating ${page.route} (${page.routeSlug})...`);
    const perPagePrompt = [
      fullPrompt,
      "",
      `--- THIS GENERATION TARGETS: ${page.route} ---`,
      `Purpose: ${page.purpose}`,
      "Render JUST this page. Header + main content + footer (as appropriate for the layout group).",
    ].join("\n");

    const screen = await project.generate(perPagePrompt);
    log("stitch", `  → screenId=${screen.screenId}, downloading html...`);

    const htmlUrl = await screen.getHtml();
    const htmlResp = await fetch(htmlUrl);
    if (!htmlResp.ok) {
      throw new Error(`HTML download for ${page.route} returned HTTP ${htmlResp.status}`);
    }
    const rawHtml = await htmlResp.text();
    if (rawHtml.length < 100) {
      log("stitch", `  WARN: html for ${page.route} is only ${rawHtml.length} chars — keeping but flagging`);
    }
    screens.push({
      screenId: screen.screenId,
      routeSlug: page.routeSlug,
      pageRoute: page.route,
      rawHtml,
    });
    log("stitch", `  ✓ ${page.route} captured (${rawHtml.length} chars)`);
  }

  // designMd: not exposed cleanly by the current SDK as a tool we can call
  // standalone; we synthesise a minimal one from the prompt. The fixture
  // schema requires ≥20 chars, and the Visual Adapter doesn't depend on a
  // specific format — it just gets persisted to .atelier/stitch-design.md.
  const designMd = [
    "# Yoga studio — design system snapshot (synthesised by recorder)",
    "",
    "Visual direction: Calm vibe, salvia green primary (#4a7c59), Inter body, Cormorant Garamond headings.",
    "Source prompt:",
    "",
    fullPrompt,
  ].join("\n");

  return { projectId: project.projectId, designMd, screens };
}

// ─── Attempt-0 mutation: simulate "Stitch forgot the <form> on /sign-in" ─

function mutateForAttempt0(screens: GeneratedScreen[]): GeneratedScreen[] {
  return screens.map((s) => {
    if (s.pageRoute !== "/sign-in") return s;
    // Strip ALL <form>...</form> blocks. The stitch-completeness-scanner's
    // signin-form heuristic looks for <form> with sign-in/login/auth hints
    // in class/id/aria-label/inner text. By removing every <form>, we
    // guarantee the scanner detects the gap on attempt 0.
    const stripped = s.rawHtml.replace(/<form[\s\S]*?<\/form>/gi, "<!-- form intentionally removed for attempt-0 fixture -->");
    if (stripped === s.rawHtml) {
      // Stitch didn't emit a <form>? Inject a "broken sign-in" marker so
      // the scanner still sees the gap. This keeps the convergence test
      // meaningful even if Stitch generated a non-<form>-based signin.
      const noForm = `<!doctype html><html><body><header><nav><a href="/">Home</a></nav></header><main><h1>Sign in</h1><p>Form will be wired manually — placeholder for attempt 0.</p></main></body></html>`;
      return { ...s, rawHtml: noForm };
    }
    return { ...s, rawHtml: stripped };
  });
}

// ─── Main ──────────────────────────────────────────────────────────

async function main(): Promise<number> {
  const repoRoot = resolve(__dirname, "..");
  const fixtureOutPath = join(repoRoot, "fixtures", "stitch-yoga.json");
  const rawHtmlDir = join(repoRoot, ".atelier-fixtures", "stitch-yoga-raw");

  log("init", "yoga PRD fixture exists check...");
  await readFile(join(repoRoot, "fixtures", "yoga-prd.json"), "utf8"); // throws if missing

  log("init", `output fixture path: ${fixtureOutPath}`);
  log("init", `raw HTML debug dir:  ${rawHtmlDir}`);

  // B3 fix — derive page list from the actual architect output, not from
  // a hardcoded memory of the yoga PRD. This guarantees the fixture's
  // pageRoutes match what `wave-1-planning` will produce when the main
  // pipeline runs, so the Layout Architect doesn't have to do creative
  // route remapping inside stitch-analysis.json.
  const architect = await runArchitectForYogaPrd();
  const pages = flattenArchitectRoutes(architect);
  log("init", `pages derived from architect: ${pages.length}`);
  for (const p of pages) log("init", `  ${p.route}  (slug=${p.routeSlug})`);

  // Generate all screens (attempt 1 = corrected set).
  const { projectId, designMd, screens } = await generateAllScreens(pages);
  log("recorder", `all ${screens.length} screens generated. projectId=${projectId}`);

  // Persist raw HTML for inspection.
  await mkdir(rawHtmlDir, { recursive: true });
  for (const s of screens) {
    await writeFile(join(rawHtmlDir, `${s.routeSlug}.html`), s.rawHtml, "utf8");
  }
  log("recorder", `raw HTML written to ${rawHtmlDir}/`);

  // Build attempt-aware fixture.
  const attempt0Screens = mutateForAttempt0(screens);
  const fixture: StitchFixture = {
    stitchProjectId: projectId,
    designVibe: "Calm",
    designMd,
    notes: `Recorded ${new Date().toISOString()} via scripts/record-stitch-yoga-fixture.ts. attempt 1 = raw Stitch output; attempt 0 = same but with /sign-in <form> stripped to exercise the stitch-completeness-scanner reprompt loop.`,
    attempts: [
      {
        attempt: 0,
        screens: attempt0Screens.map((s) => ({
          screenId: s.screenId + "-attempt-0",
          routeSlug: s.routeSlug,
          pageRoute: s.pageRoute,
          rawHtml: s.rawHtml,
        })),
      },
      {
        attempt: 1,
        screens: screens.map((s) => ({
          screenId: s.screenId,
          routeSlug: s.routeSlug,
          pageRoute: s.pageRoute,
          rawHtml: s.rawHtml,
        })),
      },
    ],
  };

  await mkdir(join(repoRoot, "fixtures"), { recursive: true });
  await writeFile(fixtureOutPath, JSON.stringify(fixture, null, 2), "utf8");
  log("done", `fixture written: ${fixtureOutPath}`);
  log("done", `duration: ${((Date.now() - TAG_START) / 1000).toFixed(1)}s`);
  return 0;
}

main().then(
  (code) => process.exit(code),
  (err) => {
    console.error("[fatal]", err);
    process.exit(99);
  },
);
